OUTPUT_DIR: "./logs/cuhk_softmax_10boxreg/transhead_hat1_1loss"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "data/CUHK-SYSU"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 16
  LR_DECAY_MILESTONES: [10, 14]
  BASE_LR: 0.0024
  LW_BOX_REID_1ST: 1.0
  LW_BOX_SOFTMAX_1ST: 0.01
MODEL:
  ROI_HEAD:
    TRANSFORMERHEAD_DEPTH: 1
    TRANSFORMERHEAD_FEATNAME: ["feat_res4"]
    NAE_FEATNAME: ["trans_feat"]
    TRANSFORMERHEAD_INCHANNELS: [1024]
    TRANSFORMERHEAD_OUTPUT_DIM: [2048]
    TRANSFORMERHEAD_SPACIAL_SIZE: [14]
    TRANSFORMERHEAD_DIM: 512
    NAE_INDV_DIM: [256]
    BATCH_SIZE_TRAIN: 80
    POS_FRAC_TRAIN: 1.0

  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
    USE_SOFTMAX: True
EVAL_USE_CBGM: False
EVAL_USE_CACHE: False